{
  "PL_TARGET_DENSITY": 0.3,
  "CLOCK_PERIOD": 1.0,
  "CLOCK_PORT": "clk",
  "SDC_FILE": "src/timing.sdc",
  "PL_RESIZER_HOLD_SLACK_MARGIN": 0.1,
  "GLB_RESIZER_HOLD_SLACK_MARGIN": 0.05,
  "RUN_LINTER": 1,
  "DIE_AREA": "0 0 220.0 160.0",
  "PL_RESIZER_HOLD_MAX_BUFFER_PERCENT": 70,
  "DPL_CELL_PADDING": 4,
  "RUN_CTS": 1,
  "RT_MAX_LAYER": "met4",
  "MAGIC_WRITE_LEF_PINONLY": 1,
  "PL_RESIZER_BUFFER_OUTPUT_PORTS": 1,
  "GRT_REPAIR_ANTENNAS": 1,
  "RUN_HEURISTIC_DIODE_INSERTION": 1,
  "PL_RESIZER_ALLOW_SETUP_VIOLATIONS": 0
}
