name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Add this step to install the missing Typst compiler
      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@tt08
