name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y iverilog
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r test/requirements.txt
      - name: Run Fuzzer
        run: |
          cd test
          make clean
          make MODULE=test_fuzzer || echo "Simulation Failed"
          if [ -f results.xml ]; then ! grep failure results.xml; else exit 1; fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: test/results.xml
